name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install dependencies"
      run: |
       sudo apt update
       sudo apt install libpng-dev libsdl2-dev libsdl2-ttf-dev gettext
       wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lua5.4/liblua5.4-0_5.4.0-2_amd64.deb
       sudo dpkg -i liblua5.4-0_5.4.0-2_amd64.deb
       wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lua5.4/liblua5.4-dev_5.4.0-2_amd64.deb
       sudo dpkg -i liblua5.4-dev_5.4.0-2_amd64.deb
    - name: "Build"
      run: |
       UNIT_TEST=1 make -j
    - name: "Run"
      run: |
       bin/main
