name: Build

on:
  - push
  - pull_request
  - release

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "Install"
      uses: awalsh128/cache-apt-pkgs-action@v1.1.3
      with:
        packages: cmake make libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libsdl2-dev libsdl2-ttf-dev libtbb-dev libassimp-dev ccache gcc-11 g++-11
        version: 1.0
    - name: "Use ccache"
      uses: hendrikmuhs/ccache-action@v1.2
    - name: "CMake build"
      uses: actions/cache@v3
      with:
        key: cmake-dependencies
        path: |
          build/_deps
    - name: "Build"
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -B build/ .
        ln -s ../mods mods
        cd build
        cmake --build . -- -j$(nproc)
        cd ..
      env:
        CC:   gcc-11
        CXX:  g++-11

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SOE-release-linux
        path: |
          build/SymphonyOfEmpires

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: lukka/get-cmake@latest

    - name: Configure Build Files
      run: |
        cmake . -G "Visual Studio 17 2022" --preset=Debug -B build

    - name: Build Symphony of Empires
      run: |
        cmake --build build --parallel --target SymphonyOfEmpires

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SOE-release-windows
        path: |
          build/SymphonyOfEmpires.exe
          build/SDL2_ttfd.dll
          build/SDL2d.dll
